### ISSUE TITLE
Link non funzionanti

### ISSUE THREAD

**Issue by Carlo-Mava** [pcm-dpc/DPC-Bollettini-Criticita-Idrogeologica-Idraulica#2]
I link del readme indicano pagine inesistenti:
- https://www.protezionecivile.gov.it/servizio-nazionale/attivita/previsione/rete-centri-funzionali
- https://www.protezionecivile.gov.it/attivita-rischi/meteo-idro/attivita/previsione-prevenzione/centro-funzionale-centrale-rischio-meteo-idrogeologico
- https://www.protezionecivile.gov.it/attivita-rischi/meteo-idro/attivita/previsione-prevenzione/centro-funzionale-centrale-rischio-meteo-idrogeologico/allertamento-meteo-idro
- https://www.protezionecivile.it/amministrazione-trasparente/provvedimenti/dettaglio/-/asset_publisher/default/content/direttiva-27-febbraio-2004-indirizzi-operativi-per-la-gestione-del-sistema-di-allertamento-nazionale-per-il-rischio-idrogeologico-e-idraulico

**Comment by stefano-calabrese** [comment]
Sostituiti i link al nuovo sito istituzionale
