### ISSUE TITLE
RSS feed - Internal Server Error

### ISSUE THREAD

**Issue by caiosweet** [pcm-dpc/DPC-Bollettini-Criticita-Idrogeologica-Idraulica#5]
Salve.
Il link rss per [Bollettini di criticità](https://dpc-web-api.protezionecivile.gov.it/rss/dpcPortalGenerateRss?categoria=bollettino_criticita), presente sul  [sito](https://www.protezionecivile.gov.it/it/rss/)
non funziona.

Stessa cosa per [Bollettini di Vigilanza Meteo nazionale](https://dpc-web-api.protezionecivile.gov.it/rss/dpcPortalGenerateRss?categoria=bollettino_vigilanza)

**Comment by aborruso** [comment]
Credo che adesso funzionino. Se sì, chiuderei

**Comment by caiosweet** [comment]
Corretto! Grazie.
